  ## MANDATORY. The URL you want to call
  # ex. http://192.168.100.2:8384 or https://mydomain.com
- url: <INSERT HTTP OR HTTPS URL>
  ## MANDATORY. The URL you use to access the GUI. Note that if you are accessing the local syncthing instance, you need to have both containers be in the same docker network, and then just use the name of the syncthing container like http://syncthing:8384
  # ex. can be `GET`, `OPTIONS`, `HEAD`, `POST`, `PUT`, `PATCH`, or `DELETE`
  http_method: <INPUT THE HTTP METHOD>
  ## OPTIONAL. You can set the payload here in json format. NOTE YOU CAN DELETE THIS FIELD ENTIRELY IF YOU'RE NOT USING IT
  # ex. {"field1":"value1","field2":"value2"}
  payload: <INSERT YOU JSON PAYLOAD>
  ## OPTIONAL. You can set the HEADERS here. NOTE THAT THE fields `key` and `value` must be present if this HEADERS object is specified. Also note that the `key` and `value` is a list, so you can specify multiple headers.
  headers:
    - key: key1
      value: val1
    - key: key2
      value: val2
  ## SINCE THIS YAML FILE IS AN ARRAY YOU CAN SEE THAT WE HAVE THE SAME SCHEMA BELOW (BUT WE'VE REMOVED THE PAYLOAD AND HEADERS)
- url: <INSERT HTTP OR HTTPS URL>
  http_method: <INPUT THE HTTP METHOD>
